---
title: "app example Rmd_imgesu"
author: "Imgesu Cetin"
date: "8/22/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#data 
library(shiny)
library(plotly)
library(gtrendsR)
library(readr)
asylum<-read.csv('asylumdata_new.csv')
#source("Function_Rshiny.R")
library(shinydashboard)
data("countries")
#Migrationd<-read.csv('migrationdata_new.csv')
library(readxl)
iso<- read_excel("iso_country_lang_data.xlsx")

str(Migrationdata$Year)
str(asylum_applications_UNHCR$Year)

unique(Migrationdata$Country)
unique(Migrationdata$Country.of.birth.nationality)
#standardize country names 
library(StandardizeText)
Migrationdata$origin.stand<-standardize.countrynames(Migrationdata$Country.of.birth.nationality,standard="iso",suggest="auto")
Migrationdata$destination.stand<-standardize.countrynames(Migrationdata$Country,standard="iso",suggest="auto")
#asylum data
asylum$origin.stand<-standardize.countrynames(asylum$Country.of.origin,standard="iso",suggest="auto")

asylum$destination.stand<-standardize.countrynames(asylum$Country.of.asylum,standard="iso",suggest="auto")

unique(Migrationdata$origin.stand)
write.csv(Migrationdata,"migrationdata_new.csv")
write.csv(asylum,"asylumdata_new.csv")
#the new variables are origin.stand and destination.stand
```
```{r}
unique(asylum$origin.stand)
asylum$
```

```{r}
#Function
###############################################################
library(gtrendsR)
library("dplyr")
library("stringr")
library(ggplot2)
library("tidyverse")
library(ggpubr)

###############################################################


# rm(list = ls())
# normalize to scale 0-100
normalized <- function(x){
  ((x-min(x))/(max(x)-min(x)))*100
}



####################  Total migration OECD  ####################
# Migration total - OECD
#Migrationdata <- read_csv("migrationdata_new.csv")
Migrationdata$Year<- as.integer(Migrationdata$Year)
# Function for Aggregating and filtering the Migration data.
Agg_filter_migration <- function(Migrationdata, origin,
                                destination, Year_from, Year_till){
  # Detect the Inflows and aggregate
  Migrationdata_agg <- Migrationdata %>%  
    filter(str_detect(Variable, "^Inflows")) %>% 
    group_by(origin.stand, destination.stand, Year) %>% 
    summarise(Value = sum(Value))
  # Filter by country of origin and destination
  mig_data_1 <- Migrationdata_agg %>%  
    filter(origin.stand == origin,
           destination.stand == destination,
           Year > Year_from, Year < Year_till)
  # Normalize the migration data into 0-100 scale.
  mig_data_2 <- mig_data_1 %>%  ungroup() %>% 
    select(Year, Value) %>%
    mutate_if(is.integer, as.character) %>% 
    mutate(migration_flow_total = normalized(Value)) %>% 
    select(-Value)
  
  return(mig_data_2)
  
}
# This also works
#A<-Agg_filter_migration(Migrationdata, origin="Turkey",
#                                destination="Germany", Year_from=2001, Year_till=2014)

######################### Asylum OECD   ####################
# Function for Aggregating and filtering the Asylum-OECD
Agg_filter_OECDasylum <- function(Migrationdata, origin,
                                 destination, Year_from, Year_till){
  # Detect the Inflows and aggregate
  Asylum_OEDC <-  Migrationdata %>% 
    filter(str_detect(Variable, "^Inflows of asylum")) %>% 
    group_by(origin.stand, destination.stand, Year) %>% 
    summarise(Value = sum(Value))
  
  # Filter by country of origin and destination
  Asylum_OEDC_1 <- Asylum_OEDC %>%  
    filter(origin.stand == origin,
           destination.stand == destination,
           Year > Year_from, Year < Year_till)
  
  # Normalize the migration data into 0-100 scale.
  Asylum_OEDC_2 <- Asylum_OEDC_1 %>%  ungroup() %>% 
    select(Year, Value) %>%
    mutate_if(is.integer, as.character) %>% 
    mutate(Asylum_OEDC = normalized(Value)) %>% 
    select(-Value)
  
  return(Asylum_OEDC_2)
  
}
#This also works
#D<-Agg_filter_OECDasylum(Migrationdata, origin="Turkey",
 #                                destination="Germany", Year_from=2000, Year_till=2015)

########################## Asylum - UNHCR ###################
#asylum<-read.csv("asylum-applications_data.csv")
#asylum <- read.csv("asylumdata_new.csv")

Agg_UNHCR_asylum<- function(asylum, origin_asylum,
                            destination_asylum){
  
  # Detect the Inflows and aggregate
  Asylum_UNHCR_agg<-asylum%>%
    group_by(origin.stand , destination.stand , Year) %>%
    summarise(Value_asylum=sum(applied))
  
  # Filter by country of origin and destination
  aslyum_UNHCR_1 <- Asylum_UNHCR_agg %>%  
    filter(origin.stand == origin_asylum,
           destination.stand == destination_asylum)
  
  # Normalize the migration data into 0-100 scale.
  aslyum_UNHCR_2 <- aslyum_UNHCR_1 %>% ungroup() %>% 
    select(Year, Value_asylum) %>%
    mutate(Year = as.character(Year),
           Asylum_UNHCR = normalized(Value_asylum)) %>% 
    select(-Value_asylum)
  
  return(aslyum_UNHCR_2)
  
}
#this works
# C <- Agg_UNHCR_asylum(asylum,
#                  "Turkey",
#                  "Germany")
######################## Migration flows Data frame ################
Migration_DT <- function(Migrationdata, asylum,
                         origin,destination,
                         Year_from,Year_till,
                         origin_asylum, destination_asylum){
  
  Migration_OECD <- Agg_filter_migration(Migrationdata, origin,
                                         destination, Year_from, Year_till)
  
  Asylum_OECD <- Agg_filter_OECDasylum(Migrationdata, origin,
                                      destination, Year_from, Year_till)
  
  Asuylum_UNHCR <- Agg_UNHCR_asylum(asylum,
                                    origin_asylum,
                                     destination_asylum)
  
  DT <- Migration_OECD %>% 
    left_join(Asylum_OECD, by = "Year") %>% 
    left_join(Asuylum_UNHCR, by = "Year")
  
  return(DT)
}
# This also works
#DT <- Migration_DT(Migrationdata,asylum,
 #             origin = "Turkey",destination = "Germany",
 #             Year_from = 2005,Year_till = 2018,
 #             origin_asylum = "Turkey",
  #            destination_asylum = "Germany")
# 



######################### Google trends data ######################

# Function for aggregating the GT data as yearly basis.
Agg_yearly <- function(GTdata){
  
  Yearly_data <- GTdata[[1]]  %>% 
    mutate(Year =str_extract(date, "^.{4}")) %>% 
    mutate(hits = gsub("[^0-9.-]", "", hits)) %>% 
    group_by(Year, geo) %>% 
    summarise(hits_average = mean(as.numeric(hits))) %>% ungroup()
  
  return(Yearly_data)
  
  
}

GT_dataframe <- function(serach_terms = NA, origin_code,
                                language = "en",
                                category =0){
  
  # Make a dataframe first.
  
  # Approach 1 (Destination as keywords, category as 555)
  GT_1<-gtrends(keyword = serach_terms,geo=c(origin_code), 
                category = category,
                time='2005-01-01 2017-12-31',hl=language,
                gprop = "web", onlyInterest = TRUE)
  GT_1_agg <- Agg_yearly(GT_1) %>% ungroup() %>%
    select(Year, hits_average) %>% 
    rename(Approach_1_hits = hits_average)
  # Approach 2 (Destination as keywords, without category)
  GT_2<-gtrends(keyword = serach_terms,geo=c(origin_code),
                time='2005-01-01 2017-12-31',hl=language,
                gprop = "web", onlyInterest = TRUE)
  GT_2_agg <- Agg_yearly(GT_2) %>% ungroup() %>%
    select(Year, hits_average) %>% 
    rename(Approach_2_hits = hits_average)
  # Aprroach 3 (Category as 555 Without any keywords)
  GT_3<-gtrends(geo=c(origin_code), 
                category = category,
                time='2005-01-01 2017-12-31',hl=language,
                gprop = "web", onlyInterest = TRUE)
  GT_3_agg <- Agg_yearly(GT_3) %>% ungroup() %>%
    select(Year, hits_average) %>% 
    rename(Approach_3_hits = hits_average)
  
  GT_data <- GT_1_agg %>% 
    left_join(GT_2_agg, by = "Year") %>% 
    left_join(GT_3_agg, by = "Year")
  
  return(GT_data)
}
# This works
# gtrentA <- GT_dataframe(serach_terms = 'Germany', origin_code = 'SY',
#          language = "ar",
 #         category = 555)
# 
# 

 
# 
# # full data frame
# DT_GT <- B %>% left_join(A, by = "Year")


# Generate the comparison dashboard

Dashboard_DT <- function(Migrationdata,asylum,
                      origin,destination,
                      Year_from,Year_till,
                      origin_asylum, destination_asylum,
                      serach_terms, origin_code,
                      language ,category){
  
  DT <- Migration_DT(Migrationdata, asylum,
                     origin,destination,
                     Year_from,Year_till,
                     origin_asylum, destination_asylum)
  
  # Google trends
  GT <- GT_dataframe(serach_terms, origin_code,
         language, category)
  
  # full dataframe
  DT_GT <- DT %>% left_join(GT, by = "Year")
  
  return(DT_GT)
  
  
}


# Visualization
Dashboard_plot <- function(DT_GT){
  # x axis scale
  Scale_x <- scale_x_continuous(breaks = waiver(), n.breaks = 7)
  # Migraiton total
  A <- ggplot(data=DT_GT, aes(x=as.integer(Year))) +
    geom_line(aes(y=migration_flow_total),color = "blue", group = 1) + 
    labs(title ="Migration Inflows", y = "", x= "") + 
    ylim(0,100) + Scale_x
  # Asylum OECD
  B <- ggplot(data=DT_GT, aes(x=as.integer(Year))) +
    geom_line(aes(y=Asylum_OEDC),color = "red", group = 1) +
    labs(title ="Asylum OECD", y = "",x= "", size = 8) + ylim(0,100)+ Scale_x
  # Asylum UNHCR
  C <- ggplot(data=DT_GT, aes(x=as.integer(Year))) +
    geom_line(aes(y=Asylum_UNHCR),color = "red", group = 1) +
    labs(title ="Asylum UNHCR", y = "",x= "") + 
    ylim(0,100) + xlim(2014,2017)
  
  ######## Google Trends ##########
  # Approach 1
  p <- ggplot(data=DT_GT, aes(x=as.integer(Year))) +
    geom_line(aes(y=Approach_1_hits),color = "Green", group = 1) +
    ylim(0,100) 
  # Approach 2
  q <- ggplot(data=DT_GT, aes(x=as.integer(Year))) +
    geom_line(aes(y = Approach_2_hits), color = "black",group = 1) +
    labs(y = "A2", x= "") + ylim(0,100)
  # Approach 3
  d <- ggplot(data=DT_GT, aes(x=as.integer(Year))) +
    geom_line(aes(y = Approach_3_hits), color = "navy",group = 1) +
    labs(y = "A3", x= "") + ylim(0,100)
  
  
  ggarrange(A,B,C,
            p +labs(y="A1", x= "")+ Scale_x,
            p +labs(y="", x= "")+ Scale_x,
            p + labs(y="", x= "") + xlim(2014,2017),
            q +labs(y="A2", x= "")+ Scale_x,
            q +labs(y="", x= "")+ Scale_x,
            q + labs(y="", x= "") + xlim(2014,2017),
            d +labs(y="A3", x= "")+ Scale_x,
            d +labs(y="", x= "")+ Scale_x,
            d + labs(y="", x= "") + xlim(2014,2017),
            heights = c(2, 2),
            ncol = 3, nrow = 4)
}

 DT_GT <- Dashboard_DT(Migrationdata, asylum,
           origin = "Turkey",destination = "Germany",
           Year_from = 2005,Year_till = 2018,
           origin_asylum = "Turkey",
           destination_asylum = "Germany",
           serach_terms = 'Germany', origin_code = 'TR',
           language = "en",category = 555)

Dashboard_plot(DT_GT)
```



```{r}
#install.packages("shinythemes")
library(shinythemes)
library(shiny)
library(plotly)
library(gtrendsR)
library(readr)
library(ggplot2)
library(dplyr)

##### user interface #############
ui<-fluidPage(theme = shinytheme("cerulean"),
    titlePanel("Google Trends Index for Forecasting Migration"),
    sidebarLayout(
      sidebarPanel(
        #select country
        selectInput("geo", label = h5("Select Origin Country for Google Trends"),
                    choices = unique(iso$iso), selected = "TR"),
        selectInput("lang", label=h5("Origin language"),choices= unique(iso$hl),selected = "en"),
          
        selectInput("queries", label = h5("Destination for Google Trends"),
                   choices=unique(Migrationdata$origin.stand),selected = "Germany" ),
        selectInput("Migration.origin", label = h5("Migration flows Data origin"),
                   choices=unique(Migrationdata$Country.of.birth.nationality),selected = "Turkey" ),
        selectInput("Migration.destination", label = h5("Migration Destination"),
                   choices=unique(Migrationdata$Country),selected = "Germany"),
        selectInput("Asylum.destination", label = h5("Asylum Destination"),
                   choices=unique(asylum$Country.of.asylum),selected = "Germany"),
    selectInput("Asylum.origin", label = h5("Asylum Origin"),
                   choices=unique(asylum$Country.of.origin),selected = "Turkey")),
    
    #puts all plots on different tabs. Maybe we can add graphs here
    mainPanel( plotOutput("plot1",height=700)
                
                
        
            )
            
        )
    )




## server.R ##
library(shiny)
library(shinydashboard)
library(gtrendsR)
library(ggplot2)
library(stringr)
library(ggpubr)
library("dplyr")
library("stringr")
library("tidyverse")
library(ggpubr)


server<-function(input, output) {


    data("countries")
    
    #dataInput <- reactive({
     #   gtrends(keyword = input$queries,
     #           geo = input$geo,
     #           time = input$time,
     #           hl= input$lang)
   # })
    
   # output$plot1 <- renderPlot({
      #plot for all
       # res <- dataInput()
       # plot(res)
   # })
  #this uses the newest function
   dataInput <- reactive({
     Dashboard_DT(Migrationdata,
                 asylum,
                 origin = input$Migration.origin,
                 destination = input$Migration.destination,
                 Year_from = 2005,
                 Year_till = 2015,
                 origin_asylum = input$Asylum.origin,
                 destination_asylum = input$Asylum.destination,
                 serach_terms = input$queries,
                 origin_code = input$geo,
                 language = input$lang,
                 category = 555)
  #this uses the first original function
     # Generate_comparison(serach_terms = input$queries,
     #                      origin_code = input$geo,
     #                       language = input$lang,
      #                      origin = input$Migration.origin,
      #                      destination = input$Migration.destination,
       #                     origin_asylum = input$Asylum.origin,
       #                     destination_asylum = input$Asylum.destination)
    })
   output$plot1<- renderPlot({
     res<-dataInput()
     Dashboard_plot(res)
    
    
      
    })
    
}

shinyApp(ui=ui,server = server)


```


