---
title: "Functions_new_imgesu"
author: "Imgesu Cetin"
date: "8/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#preparing data
Migrationdata <- read.csv("migrationData copy.csv")
unique(Migrationdata$Variable)


Migrationdata %>% filter(str_detect(Variable, "^Inflows")) %>%
  distinct(VAR)
Migrationdata %>%  filter(VAR == "B13")

Migrationdata_agg <- Migrationdata %>%  
  filter(str_detect(Variable, "^Inflows")) %>% 
  group_by(Country.of.birth.nationality, Country, Year) %>% 
  summarise(Value = sum(Value))

#filtering OECD data for just asylum
Migrationdata_agg_asylum <- Migrationdata %>%  
  filter(str_detect(Variable, "^Inflows of asylum")) %>% 
  group_by(Country.of.birth.nationality, Country, Year) %>% 
  summarise(Value_asylum = sum(Value))



#asylum data from UNHCR. This data is incomplete
asylum_applications_data <- read_csv("asylum-applications_data.csv")


Asylum_data_agg<-asylum_applications_data%>%
  group_by(`Country of origin`,`Country of asylum`,Year) %>%
  summarise(Value_asylum=sum(applied))


```


#Function
```{r}

Agg_yearly <- function(GTdata){
  
  Yearly_data <- GTdata[[1]]  %>% 
    mutate(Year =str_extract(date, "^.{4}")) %>% 
    mutate(hits = gsub("[^0-9.-]", "", hits)) %>% 
    group_by(Year, keyword,geo) %>% 
    summarise(hits_average = mean(as.numeric(hits))) %>% ungroup()
  
  return(Yearly_data)
  
  
}



# Funciton for Migration data filtering
Filtering_migration <- function(Migrationdata_agg, origin,
                                destination, Year_from, Year_till){
  
  mig_data_New <- Migrationdata_agg %>%  
    filter(Country.of.birth.nationality == origin,
           Country == destination,
           Year > Year_from, Year < Year_till)
  
  return(mig_data_New)
  
}
Asylum_data_agg$Year

# Funciton for Migration data filtering
Filtering_asylum<- function(Asylum_data_agg, origin_asylum,
                                destination_asylum, Year_from, Year_till){
  
  aslyum_data_New <- Asylum_data_agg %>%  
    filter(`Country of origin` == origin_asylum,
           `Country of asylum` == destination_asylum,
           Year > Year_from, Year < Year_till)
  
  return(aslyum_data_New)
  
}

# Generate the comparison plot
Generate_comparison <- function(serach_terms, origin_code,
                                language, origin, destination, origin_asylum, destination_asylum){

  # GT data
  GT<-gtrends(serach_terms,geo=c(origin_code),
                       time='2004-01-01 2017-12-31',hl=language,
                       gprop = "web", onlyInterest = TRUE)
  
  GT_year <- Agg_yearly(GT)  %>%
    ungroup() %>% 
    select(Year, hits_average)
  # Migration data
  Migration <- Filtering_migration(Migrationdata_agg,
                               origin,
                               destination, 
                               Year_from = 2005,
                               Year_till = 2018)
  Migration_1 <- Migration %>%  select(Year, Value) %>% 
    mutate_if(is.integer, as.character)
  
    Asylum <- Filtering_asylum(Asylum_data_agg,
                               origin_asylum,
                               destination_asylum, 
                               Year_from = 2005,
                               Year_till = 2018)
  Asylum_1 <- Asylum %>%  select(Year, Value_asylum) %>% 
    mutate_if(is.integer, as.character)
  
  
  # combine data
  Migration_GT_bind <- Migration_1 %>% 
    left_join(GT_year, by = "Year")
  Asylum_GT_bind <- Asylum_1 %>% 
    left_join(GT_year, by = "Year")
    
  Migration_GT_bind<- merge(Migration_GT_bind,Asylum_GT_bind, by ="Year")

  p <- ggplot(data=Migration_GT_bind, aes(x=Year)) +
    geom_line(aes(y=Value),color = "blue", group = 1) +
    labs(y="Migration Inflow")
  # GT data
  q <- ggplot(data=Migration_GT_bind, aes(x=Year)) +
    geom_line(aes(y = hits_average), color = "red",group = 1) +
    labs(y = "Yearly search hits")
  t <-ggplot(data=Migration_GT_bind, aes(x=Year)) +
    geom_line(aes(y = Value_asylum), color = "red",group = 1) +
    labs(y = "Yearly search hits")
  
  ggarrange(p, q, t, 
            labels = c("Migration flow", "Search hits","Asylum flow"),
            ncol = 1, nrow = 3)

}

```


# Generate function
```{r}
Generate_comparison(serach_terms = "Germany",
                    language = 'ar',
                    origin_code =  "IQ", 
                    origin = "Iraq",
                    destination = "Germany",
                    origin_asylum = 'Iraq',
                    destination_asylum = 'Germany')



```
# For all other cases

```{r}
```

